# Generated by Django 3.1.5 on 2021-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(default='Present', max_length=7),
        ),
    ]
