# Generated by Django 3.1.5 on 2021-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210130_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='sender_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='messages',
            new_name='message',
        ),
        migrations.AddField(
            model_name='inbox',
            name='subject',
            field=models.CharField(default='contact me', max_length=50),
        ),
    ]
