# Generated by Django 3.1.5 on 2021-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210130_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
