# Generated by Django 3.1.5 on 2021-01-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210130_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contaxt',
            new_name='contact',
        ),
    ]
