# Generated by Django 3.1.5 on 2021-01-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210130_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
